services:
  custom-hds:
    #image: alexinabox/custom-hds:dev
    image: alexinabox/custom-hds:dev
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
    volumes:
      - "./config.json:/custom-hds/config.json"
      - "/var/www/example:/custom-hds/public/plex_covers"
